version: 2
updates:
  - package-ecosystem: npm
    directory: /packages/web-composer
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - web-composer
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - ci
