export const composerStrings = {
  previewTitle: "Preview",
  copy: "Copy",
  presetLabel: "Preset",
  instructionLabel: "Instruction",
  instructionPlaceholder: "Instruction",
  providerSetupLabel: "Provider setup",
  settings: "Settings",
  nativeFileToolsLabel: "Native file tools",
  readFile: "Read File",
  save: "Save",
  diagnosticsLabel: "Runtime diagnostics",
  diagnosticsSummary: "Runtime",
  permissionsSummary: "Permissions",
  draftLabel: "Draft",
  draftPlaceholder: "Paste or type the text you want Inputo to transform...",
  clear: "Clear",
  cancel: "Cancel",
  generate: "Generate",
  generating: "Generating",
  generatingStatus: "Generating...",
  emptyPreview: "No preview yet.",
  previewRendered: "Preview rendered.",
  previewPayloadInvalid: "Preview payload could not be rendered.",
  readyToCopy: "Ready to copy.",
  noOutputReturned: "No output returned.",
  generationFailed: "Generation failed.",
  generationCancelled: "Generation cancelled.",
  generationCleared: "Generation cleared.",
  bridgeUnreadable: "Native bridge returned an unreadable message.",
  snapshotLoadFailed: "Could not load native state.",
  providerValidationDetail: "Open Settings to update the provider URL or model.",
  missingAPIKey: "Add an API key in Settings before generating.",
  missingAPIKeyDetail: "The API key stays in the native keychain and is never exposed to Web.",
  chooseReadableFile: "Choose a text file in the native picker.",
  readingFile: "Reading selected file...",
  noReadableFileSelected: "No readable file was selected.",
  loadedFile: (displayName: string) => `Loaded ${displayName}.`,
  chooseWritableFile: "Choose a save location in the native panel.",
  noWriteTargetSelected: "No write target was selected.",
  savedFile: (displayName: string) => `Saved ${displayName}.`,
  filesNeedConfirmation: "Files require native confirmation",
  filesReadOnly: "File read available; save unavailable",
  filesWriteOnly: "File save available; read unavailable",
  filesUnavailable: "Files unavailable in this mode",
  providerConfigured: "Provider configured",
  providerNeedsSetup: "Provider needs setup",
  providerUnknown: "Provider unknown",
  bundledAssets: "Bundled assets",
  noPermissionsReported: "No permissions reported",
  available: "Available",
  unavailable: "Unavailable",
  notRequired: "Not required",
  notRequested: "Not requested",
  requiresUserAction: "User action",
  denied: "Denied",
  unknown: "Unknown"
} as const;
